import { LuUser } from "react-icons/lu"
import {defineType,defineField} from "sanity"

export const startup=defineType({
    name:"startup",
    title:"Startup",
    type:"document",
    icon: LuUser,
    fields:[
        defineField(
            {
                name:'title',
                type:'string',
            }
        ),
        defineField(
            {
                name:'slug',
                type:'slug',
                options:{
                    source:'title'
                }
            }
        ),
        defineField(
            {
                name:'author',
                type:'reference',
                to:{type:'author'}
            }
        ),
        defineField(
            {
                name:'views',
                type:'number',
            }
        ),
        defineField(
            {
                name:'category',
                type:'string',
            }
        ),
        defineField(
            {
                name:'image',
                type:'url',
                validation:(Rule)=>Rule.required()
            }
        ),
        defineField(
            {
                name:'pitch',
                type:'markdown',
            }
        ),
        defineField(
            {
                name:'description',
                type:'text',
            }
        ),
    ]
})